name: Cypress CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: cypress/e2e/login
            label: login
          - folder: cypress/e2e/signup
            label: signup
          - folder: cypress/e2e/api
            label: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --spec "${{ matrix.folder }}/**/*.cy.js"

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{matrix.label}}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{matrix.label}}
          path: cypress/videos

      - name: Upload Mochawesome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ matrix.label }}
          path: cypress/reports/mocha
          if-no-files-found: ignore

  merge-reports:
    # This job runs only after all the parallel cypress-run jobs have finished.
    needs: [cypress-run]
    # This 'if' condition ensures the report is generated even if some tests fail.
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all mochawesome reports
        uses: actions/download-artifact@v4
        with:
          path: cypress/reports/all-mochawesome-reports
          pattern: mochawesome-report-*
          merge-multiple: true

      - name: Install dependencies
        run: npm ci

      - name: Merge and Generate HTML Report
        run: npm run report:merge && npm run report:generate

      - name: Upload Final HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: final-html-report
          path: cypress/reports
          if-no-files-found: ignore
